title: "Isaac Buo"
author: "Isaac Buo"
description: "University of Tartu, Estonia"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false      # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false            # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "/resume.pdf", title : "CV", icon: cv}
  - {title: "Publications"}
  - {title: "Blog", file: "blog.md"}
  #- {file: "README.md", title: "About", icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "isaac.buo@ut.ee"}
  - {title: Github, icon: github, url: "https://github.com/kwazineutin"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/neutin_kwazi"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
